public class IBMLanguageTranslatorV2FTest {
    
/*
{
  "url": "https://gateway.watsonplatform.net/language-translator/api",
  "username": "9d9e6978-95f6-4d69-921c-ce8f76b62c66",
  "password": "GCZvSvEo45hu"
}
*/

  private static String NAMED_CREDENTIALS = 'callout:watson_language_translator_v2';
  private static String VERSION_2017_05_26 = '2017-05-26';
  public static final String URLStr = 'https://gateway.watsonplatform.net/language-translator/api';
  public static final String username = '';
  public static final String password = '';
    
  /**
   *  Test translate
   */
  public static void testTranslate() {}

  /**
   *  Test identify
   */
  public static void testIdentify(){}

  /**
   *  Test Identifiable Languages
   */
  public static void testListIdentifiableLanguages(){}

  /**
   *  Test create a model
   */
  public static void testCreateModel(){}

  /**
   *  Test delete a model
   */
  public static void testDeleteModel(){}

  /**
   *  Test get model data
   */
  public static void testGetModel(){}

  /**
   *  Test list model data
   */
  public static void testListModels(){}
    
}