public class IBMLanguageTranslatorV2FTest {
    
  /**
   *  Test translate
   */
  public static void testTranslate() {}

  /**
   *  Test identify
   */
  public static void testIdentify(){}

  /**
   *  Test Identifiable Languages
   */
  public static void testListIdentifiableLanguages(){}

  /**
   *  Test create a model
   */
  public static void testCreateModel(){}

  /**
   *  Test delete a model
   */
  public static void testDeleteModel(){}

  /**
   *  Test get model data
   */
  public static void testGetModel(){}

  /**
   *  Test list model data
   */
  public static void testListModels(){}
    
}