/**
 * IBMWatsonProfile.
 */
public class IBMWatsonProfile {
  private String processedLanguage;
  private Long wordCount;
  private String wordCountMessage;
  private List<IBMWatsonTrait> personality;
  private List<IBMWatsonTrait> values;
  private List<IBMWatsonTrait> needs;
  private List<IBMWatsonBehavior> behavior;
  private List<IBMWatsonConsumptionPreferencesCategory> consumptionPreferences;
  private List<IBMWatsonWarning> warnings;
}
