{
  "environment_id": "f822208e-e4c2-45f8-a0d6-c2be950fbcc8",
  "name": "test_environment",
  "description": "Test environment",
  "created": "2016-06-16T10:56:54.957Z",
  "updated": "2017-05-16T13:56:54.957Z",
  "status": "active",
  "read_only": false,
  "index_capacity": {
    "documents": {
      "indexed": 0,
      "maximum_allowed": 1000000
    },
    "disk_usage": {
      "used_bytes": 0,
      "maximum_allowed_bytes": 85899345920
    }
  }
}